export const status = [
  { value: "", label: "All" },
  { value: "ongoing", label: "Ongoing" },
  { value: "completed", label: "Completed" },
];

export const type = [
  { value: "", label: "All" },
  { value: "tv", label: "TV Series" },
  { value: "movie", label: "Movie" },
  { value: "ova", label: "OVA" },
  { value: "live action", label: "Live Action" },
  { value: "special", label: "Special" },
  { value: "ona", label: "ONA" },
];

export const order = [
  { value: "title", label: "A-Z" },
  { value: "titlereverse", label: "Z-A" },
  { value: "update", label: "Latest Update" },
  { value: "latest", label: "Latest Added" },
  { value: "popular", label: "Popular" },
];

export const genre = [
  "Action",
  "Adventure",
  "Animation",
  "Anthropomorphic",
  "Avant Garde",
  "Award Winning",
  "Boys Love",
  "Cars",
  "CGDCT",
  "Childcare",
  "Combat Sports",
  "Comedy",
  "Crime",
  "Cultivation",
  "Delinquents",
  "Dementia",
  "Demons",
  "Detective",
  "Donghua",
  "Drama",
  "Ecchi",
  "Esports",
  "Family",
  "Fantasy",
  "Fighting",
  "Gag Humor",
  "Game",
  "Girls Love",
  "Gore",
  "Gourmet",
  "Harem",
  "Historical",
  "Horror",
  "Idols (Female)",
  "Idols (Male)",
  "Isekai",
  "Iyashikei",
  "Josei",
  "Kids",
  "Life",
  "Live Action",
  "Love Polygon",
  "Love Status Quo",
  "Magic",
  "Magical Sex Shift",
  "Mahou Shoujo",
  "Martial Art",
  "Martial Arts",
  "Mature",
  "Mecha",
  "Medical",
  "Military",
  "Millet",
  "Movie",
  "Music",
  "Mystery",
  "Mythology",
  "ONA",
  "Organized Crime",
  "Otaku Culture",
  "OVA",
  "Parody",
  "Performing Arts",
  "Pets",
  "Police",
  "Psychological",
  "Racing",
  "Reincarnation",
  "Reverse Harem",
  "Romance",
  "Romantic Subtext",
  "Samurai",
  "School",
  "Sci-Fi",
  "Seinen",
  "Shoujo",
  "Shoujo Ai",
  "Shounen",
  "Shounen Ai",
  "Showbiz",
  "Slice of Life",
  "Space",
  "Special",
  "Sports",
  "Strategy Game",
  "Super Power",
  "Supernatural",
  "Survival",
  "Suspense",
  "Team Sports",
  "Thriller",
  "Time Travel",
  "Tokusatsu",
  "Urban Fantasy",
  "Vampire",
  "Video Game",
];
